// Centralized Mock Product Data as an Array
export const mockProductsArray = [
  {
    id: "prod_001",
    cropType: "tomato", // Used for matching input
    title: "Fresh Organic Tomato Box (2kg)",
    title_ko: "신선한 유기농 토마토 박스 (2kg)",
    price: "19,000 KRW",
    image: "/placeholder.svg?height=300&width=400", // Varied dimensions
    buyLink: "/mock-shop/product/fresh-organic-tomato-box",
    description: "Premium organic tomatoes grown in sustainable farms, perfect for salads and sauces.",
    description_ko: "지속 가능한 농장에서 재배된 프리미엄 유기농 토마토로, 샐러드와 소스에 완벽합니다.",
    seller: "Green Valley Farm",
    rating: 4.8,
    inStock: true,
    slug: "fresh-organic-tomato-box", // Used for URL routing
    category: "Vegetables",
    tags: ["organic", "fresh", "local", "sustainable", "tomato"],
  },
  {
    id: "prod_002",
    cropType: "carrot",
    title: "Premium Carrot Bundle (1.5kg)",
    title_ko: "프리미엄 당근 묶음 (1.5kg)",
    price: "12,500 KRW",
    image: "/placeholder.svg?height=320&width=420", // Varied dimensions
    buyLink: "/mock-shop/product/premium-carrot-bundle",
    description: "Sweet and crunchy carrots, ideal for juicing, roasting, or snacking.",
    description_ko: "달콤하고 아삭한 당근으로, 주스, 로스팅 또는 간식으로 이상적입니다.",
    seller: "Sunrise Agriculture",
    rating: 4.6,
    inStock: true,
    slug: "premium-carrot-bundle",
    category: "Vegetables",
    tags: ["sweet", "crunchy", "vitamin-rich", "carrot"],
  },
  {
    id: "prod_003",
    cropType: "lettuce",
    title: "Fresh Lettuce Head (3 pieces)",
    title_ko: "신선한 상추 (3개)",
    price: "8,900 KRW",
    image: "/placeholder.svg?height=280&width=380", // Varied dimensions
    buyLink: "/mock-shop/product/fresh-lettuce-head",
    description: "Crisp and fresh lettuce heads for vibrant salads and healthy wraps.",
    description_ko: "아삭하고 신선한 상추로, 생기 넘치는 샐러드와 건강한 랩에 좋습니다.",
    seller: "Urban Greens",
    rating: 4.7,
    inStock: true,
    slug: "fresh-lettuce-head",
    category: "Leafy Greens",
    tags: ["crisp", "fresh", "salad", "healthy", "lettuce"],
  },
  {
    id: "prod_004",
    cropType: "eggplant",
    title: "Korean Eggplant (1kg)",
    title_ko: "가지 (1kg)",
    price: "15,800 KRW",
    image: "/placeholder.svg?height=310&width=410", // Varied dimensions
    buyLink: "/mock-shop/product/korean-eggplant",
    description: "Fresh Korean eggplants, perfect for traditional dishes like 가지나물 (gaji-namul).",
    description_ko: "가지나물과 같은 전통 요리에 완벽한 신선한 한국 가지입니다.",
    seller: "Heritage Farms",
    rating: 4.5,
    inStock: false,
    slug: "korean-eggplant",
    category: "Vegetables",
    tags: ["korean", "traditional", "purple", "eggplant"],
  },
  {
    id: "prod_005",
    cropType: "potato",
    title: "Organic Potato Bag (3kg)",
    title_ko: "유기농 감자 (3kg)",
    price: "16,200 KRW",
    image: "/placeholder.svg?height=290&width=390", // Varied dimensions
    buyLink: "/mock-shop/product/organic-potato-bag",
    description: "Versatile organic potatoes, a kitchen staple for mashing, frying, or baking.",
    description_ko: "으깨거나 튀기거나 굽는 등 다양한 요리에 활용 가능한 유기농 감자입니다.",
    seller: "Mountain View Farm",
    rating: 4.9,
    inStock: true,
    slug: "organic-potato-bag",
    category: "Root Vegetables",
    tags: ["organic", "versatile", "staple", "potato"],
  },
  {
    id: "prod_006",
    cropType: "banana",
    title: "Sweet Organic Banana Bunch (1kg)",
    title_ko: "달콤한 유기농 바나나 (1kg)",
    price: "9,500 KRW",
    image: "/placeholder.svg?height=330&width=430", // Varied dimensions
    buyLink: "/mock-shop/product/sweet-organic-banana-bunch",
    description: "Naturally sweet and energy-rich organic bananas, great for snacks or smoothies.",
    description_ko: "자연적으로 달콤하고 에너지 넘치는 유기농 바나나로, 간식이나 스무디에 좋습니다.",
    seller: "Tropical Harvest",
    rating: 4.7,
    inStock: true,
    slug: "sweet-organic-banana-bunch",
    category: "Fruits",
    tags: ["organic", "sweet", "fruit", "banana"],
  },
  {
    id: "prod_007",
    cropType: "radish",
    title: "Crisp Red Radish (500g)",
    title_ko: "아삭한 빨간 무 (500g)",
    price: "7,200 KRW",
    image: "/placeholder.svg?height=270&width=370", // Varied dimensions
    buyLink: "/mock-shop/product/crisp-red-radish",
    description: "Fresh, crisp red radishes with a peppery bite, perfect for salads.",
    description_ko: "톡 쏘는 맛이 있는 신선하고 아삭한 빨간 무로, 샐러드에 완벽합니다.",
    seller: "Garden Fresh Co.",
    rating: 4.3,
    inStock: true,
    slug: "crisp-red-radish",
    category: "Vegetables",
    tags: ["crisp", "red", "salad", "radish"],
  },
  {
    id: "prod_008",
    cropType: "pumpkin",
    title: "Mini Sweet Pumpkin (1 piece)",
    title_ko: "미니 단호박 (1개)",
    price: "11,000 KRW",
    image: "/placeholder.svg?height=340&width=440", // Varied dimensions
    buyLink: "/mock-shop/product/mini-sweet-pumpkin",
    description: "Small, sweet pumpkins ideal for roasting, soups, or decorative purposes.",
    description_ko: "로스팅, 수프 또는 장식용으로 이상적인 작고 달콤한 호박입니다.",
    seller: "Autumn Fields",
    rating: 4.6,
    inStock: true,
    slug: "mini-sweet-pumpkin",
    category: "Vegetables",
    tags: ["sweet", "seasonal"],
  },
]
